### PR TITLE
proto: use v2 of Protobuf

### PR DESCRIPTION
**Pull request by mewmew**
The CI system has not yet been update to download
the needed tools for protobuf v2 generation, these
are:

   go get -u google.golang.org/protobuf/cmd/protoc-gen-go
   go get -u google.golang.org/protobuf/cmd/protoc-gen-go-grpc

Note: protoc-gen-go-grpc will move to google.golang.org/grpc
in the future (see golang/protobuf#903).

Tentative fix of #10.

### CODE REVIEW

**Comment by karlek** [comment]
I'll update `karlekdocker/pippi`, so when the PR is merged you can just rebase to rerun the tests.

**Comment by mewmew** [comment]
> I'll update karlekdocker/pippi, so when the PR is merged you can just rebase to rerun the tests.

Great!

I'm troubleshooting a few issues with the v2 generated protobuf code. It may still be a bit early for us to start using v2.

**Edit:** I wish that for cases like these thank you could "downgrade" a PR to a draft PR. But it seems like you can only go from [draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/) -> PR and not the other direction.

**Comment by karlek** [comment]
> > I'll update karlekdocker/pippi, so when the PR is merged you can just rebase to rerun the tests.
> 
> Great!
> 
> I'm troubleshooting a few issues with the v2 generated protobuf code. It may still be a bit early for us to start using v2.
> 
> **Edit:** I wish that for cases like these thank you could "downgrade" a PR to a draft PR. But it seems like you can only go from [draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/) -> PR and not the other direction.

Just create a new PR as draft?

**Comment by mewmew** [comment]
> Just create a new PR as draft?

Will do.

**Pull request closed without merging**
